REPORTS_RENAME = {
    "safetyreportid": "safetyreportid",
    "safetyreportversion": "version",
    "receiptdate": "receiptdate",
    "transmissiondate": "transmissiondate",
    "primarysourcecountry": "country",
    "occurcountry": "occurcountry",
    "reporttype": "reporttype",
    "serious": "serious",
    "seriousnesscongenitalanomali": "congenital_anomaly",
    "seriousnessdeath": "death",
    "seriousnessdisabling": "disabling",
    "seriousnesshospitalization": "hospitalization",
    "seriousnesslifethreatening": "lifethreatening",
    "seriousnessother": "other_serious",
    "fulfillexpeditecriteria": "fulfillexpeditecriteria",
    "duplicate": "duplicate",
    "duplicatenumb": "duplicate_numb",
    "duplicatesource": "duplicate_source",
    "authoritynumb": "authoritynumb",
    "companynumb": "companynumb",
}
 
DEMOGRAPHICS_RENAME = {
    "safetyreportid": "safetyreportid",
    "safetyreportversion": "version",
    "patientagegroup": "age_group",
    "patientonsetage": "onset_age",
    "patientonsetageunit": "onset_age_unit",
    "patientsex": "sex",
    "patientweight": "weight",
}
 
DRUG_RENAME = {
    "safetyreportid": "safetyreportid",
    "safetyreportversion": "version",
    "medicinalproduct": "medicinalproduct",
    "activesubstancename": "active_substance",
    "drugcharacterization": "drugcharacterization",
    "drugindication": "drugindication",
    "drugauthorizationnumb": "drugauthorizationnumb",
    "drugbatchnumb": "drugbatchnumb",
    "drugadministrationroute": "administration_route",
    "drugstructuredosagenumb": "dosage_amount",
    "drugstructuredosageunit": "dosage_unit",
    "drugstartdate": "start_date",
    "drugenddate": "end_date",
    "drugtreatmentduration": "duration",
    "drugtreatmentdurationunit": "duration_unit",
    "drugrecurreadministration": "drugrecurreadministration",
    "drugrecuraction": "recurrence_action",
    "actiondrug": "actiondrug",
    "drugadditional": "drugadditional",
}
 
REACTION_RENAME = {
    "safetyreportid": "safetyreportid",
    "safetyreportversion": "version",
    "reactionmeddrapt": "reaction",
    "reactionmeddraversionpt": "meddra_version",
    "reactionoutcome": "outcome",
}